Footer
Artem0202/team-project-carpe-diem pull request #2
Opened 2023-11-25 11:30 UTC by klimisnotavailable

2023-11-25 20:10 UTC, Artem0202 requested changes
Позначив, що треба поміняти, а що прибрати.

2023-11-25 20:10 UTC, Artem0202 commented on src/partials/footer.html
> +  <div class="footer-container">
Сюди треба додати класс `container`, він як раз прописаний в файлі з базовими стилями. Тоді не треба буде ці стилі прописувати `footer-container`

2023-11-25 20:10 UTC, Artem0202 commented on src/css/footer.css
> +  margin: 0 auto;
Це прибрати, так як це прописано в класі `container`

2023-11-25 20:10 UTC, Artem0202 commented on src/css/footer.css
> +  padding: 40px 20px 292px 20px;
Тут прибрати падінги зправа та зліва, так як це прописано в класі `container`

2023-11-25 20:10 UTC, Artem0202 commented on src/css/footer.css
> +    background-repeat: no-repeat;
Цу можна не писати, так як вони прописані вище та не змінюються

2023-11-25 20:10 UTC, Artem0202 commented on src/css/footer.css
> +    background-position: 50% 100%;
Цу можна не писати, так як вони прописані вище та не змінюються

2023-11-25 20:10 UTC, Artem0202 commented on src/css/footer.css
> +    background-size: contain;
Цу можна не писати, так як вони прописані вище та не змінюються

2023-11-25 20:10 UTC, Artem0202 commented on src/css/footer.css
> +  margin-right: auto;
не бачу для чого цей падінг

2023-11-25 20:10 UTC, Artem0202 commented on src/css/footer.css
> +    background-image: url(../img/background/footerMob.png);
Це можна не писати, так як вони прописані вище та не змінюються

2023-11-25 20:10 UTC, Artem0202 commented on src/css/footer.css
> +    background-repeat: no-repeat;
Це можна не писати, так як вони прописані вище та не змінюються

2023-11-25 20:10 UTC, Artem0202 commented on src/css/footer.css
> +    background-position: 50% 100%;
Це можна не писати, так як вони прописані вище та не змінюються

2023-11-25 20:10 UTC, Artem0202 commented on src/css/footer.css
> +  @media screen and (min-resolution: 192dpi) {
Це можна не писати, так як вони прописані вище та не змінюються

2023-11-25 20:10 UTC, Artem0202 commented on src/css/footer.css
> +    margin-right: auto;
Це можна не писати, так як вони прописані вище та не змінюються

2023-11-25 20:10 UTC, Artem0202 commented on src/css/footer.css
> +    margin-left: auto;
Це можна не писати, так як вони прописані вище та не змінюються

2023-11-25 21:44 UTC, klimisnotavailable commented on src/css/footer.css
> +    background-repeat: no-repeat;
шо таке цу

2023-11-25 21:45 UTC, klimisnotavailable commented on src/css/footer.css
> +  margin-right: auto;
маржин чи падінг?

2023-11-26 16:28 UTC, Artem0202 requested changes
зроби в стилях звернення до `container` через батьківськй елемент, тобто `.footer-section .container`, бо цей клас є у інших, щоб він не перебивав стилі

2023-11-26 16:28 UTC, Artem0202 commented on src/css/footer.css
> +  margin-right: auto;
маржин, для чого він тут взагалі?

2023-11-27 18:06 UTC, Artem0202 approved these changes

2023-11-27 18:09 UTC, merged